//! Shifter — video chip of the Atari ST/STE.
//!
//! Reads video RAM line by line (at the pace of the HBL generated by
//! [`crate::peripherals::glue::Glue`]) and converts the memory bits into
//! RGB pixels according to the programmed resolution: low (320×200, 4 planes,
//! 16 colors), medium (640×200, 2 planes, 4 colors), high (640×400,
//! 1 plane, monochrome — monochrome screen only).
//!
//! This module models the chip **alone**, independent of any actual
//! display pipeline: [`Shifter::render_scanline`] takes a slice of
//! RAM and returns 24-bit RGB pixels, ready to be placed into whatever
//! host framebuffer. It is up to the board to:
//! - map [`Shifter::read`]/[`Shifter::write`] into its `Bus`,
//! - call [`Shifter::write_palette_word`] for any `.W`/`.L` CPU access
//!   touching a palette register (`$FF8240`-`$FF825E`) — unlike
//!   [`Shifter::write`], which always assumes an isolated `.B` access
//!   and duplicates the written byte into both halves of the word, real
//!   silicon behavior but wrong for a normal `.W`/`.L` write (see the
//!   doc of [`Shifter::write`]),
//! - call [`Shifter::set_ste_palette`] right after construction based on
//!   the machine model ([`crate::systems::atari_st::model::MachineProfile::ste_palette`]),
//! - call [`Shifter::start_frame`] on every VBL (reloads the video
//!   counter from the base address),
//! - call [`Shifter::render_scanline`] on every HBL, passing it its
//!   RAM (the Shifter is a second bus master, independent of the CPU —
//!   hence the DRAM/video contention generically modeled by
//!   `Bus::is_contended`/`TimedBus`, not here),
//! - route `$FF8264`/`$FF8265` (STE fine scrolling) and `$FF820F`
//!   (STE line width) to [`Shifter::write_hscroll`]/
//!   [`Shifter::write_line_width`], computing `apply_now` itself
//!   from `Glue::cycles_in_line`/`line_start_cycle`/`line_end_cycle` —
//!   only the board knows the cycle position within the line, see the
//!   doc of these two methods for the exact cycle-exact "gating".
//!
//! ## STE fine scrolling (cycle-exact, Hatari-style)
//! `$FF8264`/`$FF8265`/`$FF820F` are modeled faithfully, including the
//! cycle-exact "gating" of writes (immediate on the line currently being
//! scanned if written before the relevant threshold, deferred to the next
//! line otherwise — see [`Shifter::write_hscroll`]/[`Shifter::write_line_width`]).
//! Hatari itself does NOT do real-time pixel-by-pixel rendering: it
//! timestamps register writes during the line to decide where they
//! apply, then converts the whole line at once at HBL — exactly the
//! model already in place here ([`Shifter::render_scanline`] called once
//! per line), no pipeline rework needed.
//!
//! Deliberately out of scope (demomaking-specific bugs/effects, unrelated
//! to the scrolling mechanism itself — they touch mid-line resolution
//! change detection and per-line border tracking, no corresponding state
//! here):
//! - The "`$FF8265` then `$FF8264`=0" bug/trick (336-pixel-wide line,
//!   used by specific demos such as Pacemaker/Obsession/Skulls).
//! - Timing variants depending on STF motherboard revision (WS1-WS4) — not
//!   applicable, only an STE machine (a fixed set of constants) is targeted.
//!
//! ## Horizontal border / STE overscan (`$FF8260`/`$FF820A`, Hatari-style)
//! Modeled via [`border`]: a `border_mask` accumulated WHILE scanning
//! the current line (writes to `$FF8260`/`$FF820A` routed by the board
//! to [`Shifter::write_resolution`]/[`Shifter::write_sync`] with the
//! cycle position), consumed and reset to zero at the end of
//! [`Shifter::render_scanline`] — the same scheme as
//! `pending_h_scroll`/`pending_line_width`, but without deferral to the
//! next line (the tricks modeled here all apply to the line on which
//! the write occurs). All of the detection logic lives in Hatari
//! (`video.c`) in a **single** function, `Video_Update_Glue_State`,
//! called both for `$FF8260` (`Video_WriteToGlueRes`) and `$FF820A`
//! (`Video_Sync_WriteByte`) — reproduced here as two separate methods
//! on `Shifter` for simplicity, but the CYCLE CONSTANTS and the effects
//! IN BYTES (`BORDERBYTES_*`) are taken as-is from Hatari
//! (`video.h`/`video.c`, STE machine values).
//!
//! Mechanisms modeled after Hatari (v1, STE scope only — the original ST
//! variant of the `LEFT_OFF` trick, which requires a medium-resolution
//! "stabilizer", is not modeled):
//! - `LEFT_OFF_2_STE`: a brief switch to high resolution very early in
//!   the line (`cycles_in_line <= 4`) followed by a return to low/medium
//!   resolution EXACTLY at cycle 4 reveals +20 bytes of left border
//!   (short STE variant, without stabilizer — `video.c`, comment
//!   "no stabilizer needed").
//! - `RIGHT_OFF`: an `$FF820A` switch to 60Hz within the cycle window
//!   `]372, 376]` (junction between the nominal 60Hz/50Hz line ends)
//!   reveals +44 bytes of right border.
//! - `LEFT_PLUS_2`/`RIGHT_MINUS_2`: ±2 byte nudge (`$FF820A` switch to
//!   60Hz very early in the line, before `cycles_in_line <= 36`). Each
//!   mechanism (including `RIGHT_OFF`) has its OWN cancellation window on
//!   a return to 50Hz — taken as-is from Hatari
//!   (`Video_Update_Glue_State`), see the doc of
//!   [`Shifter::write_sync`]: `LEFT_PLUS_2` only if
//!   `cycles_in_line <= 52`, `RIGHT_MINUS_2`/`RIGHT_OFF` only if
//!   `cycles_in_line <= 376` (for `RIGHT_OFF`, this window is in
//!   practice very narrow, nearly coinciding with its trigger window).
//! - `STOP_MIDDLE`: hi-res switch in the middle of the line (`]4, 164]`,
//!   `$FF8260`) shortens the line by 106 bytes — cancellable by a
//!   return to low/medium resolution as long as `cycles_in_line <= 164`
//!   (before the "point of no return").
//! - `RIGHT_OFF_FULL`: later hi-res switch (`]164, 376]`,
//!   `$FF8260`) TOTALLY removes the right border (+44+22 bytes) AND
//!   forces `LEFT_OFF_2_STE` starting at the BEGINNING of the NEXT line
//!   (cross-line cascade, see [`Shifter::pending_left_off_next_line`]) —
//!   once triggered, not cancellable within the same line (simplification:
//!   Hatari has a cancellation window via `$FF820A`, not modeled).
//!
//! ## Medium-resolution left border / 4-bit hardware scrolling
//! (Steem SSE-style, NOT Hatari)
//! `OVERSCAN_MED_RES`/`FOUR_BIT_SCROLL` (see [`border`] and
//! [`Shifter::detect_med_res_tricks`]) refine the alignment of a left
//! border already revealed by `LEFT_OFF_2_STE` (precondition: they apply
//! ONLY if `LEFT_OFF_2_STE` is already active on the line). Unlike the
//! mechanisms above (which react to a fixed CYCLE THRESHOLD on each
//! write), these are tricks involving multiple resolution changes
//! (`$FF8260` high→medium→low) whose detection Hatari itself models via
//! a stack of special cases named after the demos that revealed them
//! ("No Cooper", "PYM", …) rather than a general rule — judged too
//! fragile to port as-is (see `ETAT.md`, Shifter section).
//! Steem SSE (another open-source ST/STE emulator) models the SAME
//! trick with a different, more general approach: instead of fixed
//! thresholds, it measures the number of cycles ACTUALLY elapsed
//! between successive resolution changes within the line, via a history
//! of `$FF8260` writes (`TGlue::CheckSideOverscan`/`PreviousShiftModeChange`/
//! `NextShiftModeChange`/`CycleOfLastChangeToShiftMode`, `glue.cpp`) — this
//! formula is reused here (`Shifter::resolution_write_history`), with the
//! cycle windows (`MEDRES_OA`/`_OB`/`_OC`) cross-verified against
//! Hatari's (convergence confirmed, see `ETAT.md`).
//!
//! **Documented limitations** (deliberate approximations relative to the
//! sources, due to being unable to verify certain internal details without
//! access to a real hardware capture):
//! - The `BORDERBYTES_*` constants are calibrated for low resolution
//!   (4 planes, consistent with `BORDERBYTES_NORMAL`=160=`Resolution::Low.bytes_per_line()`
//!   in Hatari) and applied AS-IS regardless of the effective
//!   resolution (no scaling by plane count) — the real-world use of
//!   these tricks targets almost exclusively low resolution, so this
//!   approximation has no effect in the documented/known cases.
//! - Interaction with STE fine scrolling (`$FF8264`/`$FF8265`): the
//!   revealed left/right border segments are rendered INDEPENDENTLY of
//!   the fine-scroll offset (no `scroll_src_bit` applied within the
//!   border) — only the central segment (nominal width) applies
//!   scrolling. Combining both effects simultaneously (as real STE
//!   "overscan + scroll" demos do) is therefore not faithful if BOTH
//!   are active on the same line.
//! - `RIGHT_MINUS_2` without a simultaneous `RIGHT_OFF` on the same line
//!   is not modeled as a shortening of the central segment (only as a
//!   reduction of the `RIGHT_OFF` extension, clamped to 0) — minor
//!   deviation, visual effect of ±2 pixels at worst.
//! - Cancellation of `STOP_MIDDLE` via a resolution change (`$FF8260`),
//!   not via `$FF820A` as Hatari actually does in this specific case
//!   (documented deviation, design choice).
//! - [`Shifter::detect_med_res_tricks`] does NOT reproduce the
//!   `!ShiftModeChangeAtCycle(...)` guard from the original Steem code
//!   (function not fully understood, effect assumed marginal —
//!   documented, not silent deviation); it also does not reproduce
//!   `HblPixelShift` (fine pixel-level offset, applied via the
//!   `hscroll` register in Steem for two specific cycle values) — Steem
//!   itself describes this latter value as "maybe coming from the demo
//!   author", so it is no more verified than the rest.
//!
//! ## Known limitations (v1)
//! - The video counter registers (`$FF8205`/`07`/`09`) always accept
//!   software writes (STE behavior); on the original ST, they are
//!   normally read-only.
//! - No 50/60 Hz synchronization distinct from the one already carried
//!   by the GLUE.
//! - High-resolution polarity convention (bit set to 1 = black, 0 =
//!   white): this is the most commonly documented convention, but not
//!   verified against a real hardware screen capture — to be confirmed
//!   if the image appears inverted in practice.

/// Programmed video resolution (register `$FF8260`, bits 0-1).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Resolution {
    /// 320×200, 4 planes (16 colors).
    Low,
    /// 640×200, 2 planes (4 colors).
    Medium,
    /// 640×400, 1 monochrome plane (monochrome screen only).
    High,
}

impl Resolution {
    fn from_bits(bits: u8) -> Self {
        match bits & 0b11 {
            0b00 => Resolution::Low,
            0b01 => Resolution::Medium,
            _ => Resolution::High,
        }
    }

    fn to_bits(self) -> u8 {
        match self {
            Resolution::Low => 0b00,
            Resolution::Medium => 0b01,
            Resolution::High => 0b10,
        }
    }

    /// Displayed width in pixels.
    pub fn width(self) -> usize {
        match self {
            Resolution::Low => 320,
            Resolution::Medium | Resolution::High => 640,
        }
    }

    /// Number of bitplanes.
    fn planes(self) -> usize {
        match self {
            Resolution::Low => 4,
            Resolution::Medium => 2,
            Resolution::High => 1,
        }
    }

    /// Number of video RAM bytes consumed per displayed line.
    pub fn bytes_per_line(self) -> usize {
        self.width() / 8 * self.planes()
    }
}

/// Register addresses on a real ST/STE.
pub mod addr {
    /// Video base address, high byte (bits 23-16, 256-byte alignment).
    pub const VIDEO_BASE_HIGH: u32 = 0xFF8201;
    /// Video base address, middle byte (bits 15-8).
    pub const VIDEO_BASE_MID: u32 = 0xFF8203;
    /// Video base address, low byte (bits 7-0) — STE only (allows finer
    /// alignment than the original ST's 256 bytes, which does not have
    /// this register). Missing from the earlier match arm: a read there
    /// fell back to the default end-of-bus `0xFF` instead of the actual
    /// register value — found by tracing a late DoubleFault in
    /// Rick_Dangerous.stx back to code that reconstructs the video base
    /// address from these three registers to compute a jump target:
    /// `0xFF` instead of `0x00` there made the final address odd and
    /// misaligned.
    pub const VIDEO_BASE_LOW: u32 = 0xFF820D;
    /// Current video counter, high byte.
    pub const VIDEO_COUNTER_HIGH: u32 = 0xFF8205;
    /// Current video counter, middle byte.
    pub const VIDEO_COUNTER_MID: u32 = 0xFF8207;
    /// Current video counter, low byte.
    pub const VIDEO_COUNTER_LOW: u32 = 0xFF8209;
    /// First palette register (16 consecutive words, one per color).
    pub const PALETTE_BASE: u32 = 0xFF8240;
    /// Resolution register.
    pub const RESOLUTION: u32 = 0xFF8260;
    /// STE horizontal fine scrolling, WITHOUT prefetch (see
    /// [`Shifter::write_hscroll`]) — 0-15 pixel offset in the low 4
    /// bits, but no extra word is read: the first 16 pixels of the line
    /// come out black.
    pub const HSCROLL_NO_PREFETCH: u32 = 0xFF8264;
    /// STE horizontal fine scrolling, WITH prefetch — same offset, but
    /// one extra group of 16 pixels is read per line to fill the right
    /// edge without visible loss. Standard register, used by almost all
    /// STE games/demos.
    pub const HSCROLL_PREFETCH: u32 = 0xFF8265;
    /// STE line width (extra bytes, in words minus one, added to the
    /// address advance at the end of the line — virtual screen wider
    /// than the display).
    pub const LINE_WIDTH: u32 = 0xFF820F;
}

/// Bits and constants for STE horizontal border removal, see the module
/// doc. The bit names below reuse, for mechanisms inherited from Hatari,
/// those from `video.c` (`BORDERMASK_*`) to stay cross-referenceable with
/// its code; [`OVERSCAN_MED_RES`]/[`FOUR_BIT_SCROLL`] (Steem SSE-style, not
/// Hatari) are not bound by this cross-reference constraint (the two
/// projects don't even use the same value for the latter).
pub mod border {
    /// Left border removed, short STE variant (+20 bytes) — see
    /// [`super::Shifter::write_resolution`].
    pub const LEFT_OFF_2_STE: u32 = 0x0200;
    /// Intermediate bit: high resolution armed early in the line, pending
    /// confirmation by a return to low/medium resolution exactly at cycle
    /// [`HDE_ON_HI`] — produces NO rendering effect by itself (only the
    /// conversion into [`LEFT_OFF_2_STE`] produces one), see
    /// [`super::Shifter::write_resolution`].
    pub(super) const LEFT_OFF_PENDING: u32 = 0x0001;
    /// +2 byte left border nudge (line starting earlier in 60Hz) — see
    /// [`super::Shifter::write_sync`].
    pub const LEFT_PLUS_2: u32 = 0x0002;
    /// Shortened line (-106 bytes), high-resolution switch in the middle
    /// of the line — see [`super::Shifter::write_resolution`].
    pub const STOP_MIDDLE: u32 = 0x0004;
    /// Right border removed (+44 bytes) — see
    /// [`super::Shifter::write_sync`]/[`super::Shifter::write_resolution`]
    /// (two possible triggers, see [`RIGHT_OFF_FULL`]).
    pub const RIGHT_OFF: u32 = 0x0010;
    /// TOTAL removal of the right border (+22 bytes, ON TOP OF
    /// [`RIGHT_OFF`] already counted), which also forces
    /// [`LEFT_OFF_2_STE`] on the NEXT line (cross-line cascade) — see
    /// [`super::Shifter::write_resolution`].
    pub const RIGHT_OFF_FULL: u32 = 0x0020;
    /// -2 byte right border nudge (line ending earlier in 60Hz) — see
    /// [`super::Shifter::write_sync`].
    pub const RIGHT_MINUS_2: u32 = 0x0008;
    /// Refined medium-resolution left border, Steem SSE-style
    /// (`TRICK_OVERSCAN_MED_RES`, same value as Hatari's `BORDERMASK_OVERSCAN_
    /// MED_RES`) — see
    /// [`super::Shifter::detect_med_res_tricks`].
    pub const OVERSCAN_MED_RES: u32 = 0x0040;
    /// 4-bit hardware scrolling, Steem SSE-style (`TRICK_4BIT_SCROLL`,
    /// arbitrary Rust68 value — Hatari has no bit-for-bit equivalent, see
    /// its own `BORDERMASK_LEFT_OFF_MED`, not reused here) — see
    /// [`super::Shifter::detect_med_res_tricks`].
    pub const FOUR_BIT_SCROLL: u32 = 0x0800;

    /// Cycle position at which a high-resolution switch arms
    /// [`LEFT_OFF_PENDING`] (`video.h`, `HDE_On_Hi`, STE value).
    pub(super) const HDE_ON_HI: u32 = 4;
    /// Upper (inclusive) detection window for [`STOP_MIDDLE`] — beyond
    /// this, [`RIGHT_OFF_FULL`] triggers instead (`video.h`,
    /// `HDE_Off_Hi`, STE value).
    pub(super) const HDE_OFF_HI: u32 = 164;
    /// Lower (exclusive) detection window for [`RIGHT_OFF`] (`video.h`,
    /// `HDE_Off_Low_60`, STE value).
    pub(super) const HDE_OFF_LOW_60: u32 = 372;
    /// Cancellation threshold for [`LEFT_PLUS_2`] on a return to 50Hz
    /// (`video.h`, `HDE_On_Low_60`, STE value) — see
    /// [`super::Shifter::write_sync`].
    pub(super) const HDE_ON_LOW_60: u32 = 52;
    /// Upper (inclusive) detection window for [`RIGHT_OFF`] (`video.h`,
    /// `HDE_Off_Low_50`, STE value).
    pub(super) const HDE_OFF_LOW_50: u32 = 376;
    /// Cycle threshold below which a 60Hz switch is still early enough in
    /// the line to be a [`LEFT_PLUS_2`]/[`RIGHT_MINUS_2`] nudge
    /// (`video.h`, `Preload_Start_Low_60`, STE value).
    pub(super) const PRELOAD_START_LOW_60: u32 = 36;
    /// Lower (exclusive) detection window for [`OVERSCAN_MED_RES`] (Steem
    /// SSE, `glue.cpp`, `ScanlineTiming[MEDRES_OA]`) — cross-verified
    /// against Hatari (`LINE_LEFT_MED_CYCLE_1`, same value), see the
    /// module doc.
    pub(super) const MEDRES_OA: u32 = 24;
    /// Upper (inclusive) detection window for [`OVERSCAN_MED_RES`]/
    /// [`FOUR_BIT_SCROLL`] (Steem SSE, `ScanlineTiming[MEDRES_OB]`).
    pub(super) const MEDRES_OB: u32 = 48;
    /// Lower (inclusive) detection window for [`FOUR_BIT_SCROLL`] (Steem
    /// SSE, `ScanlineTiming[MEDRES_OC]`) — cross-verified against Hatari
    /// (`LINE_LEFT_STAB_LOW`, same value).
    pub(super) const MEDRES_OC: u32 = 16;

    /// Byte effect of [`LEFT_OFF_2_STE`] (`video.h`,
    /// `BORDERBYTES_LEFT_2_STE`).
    pub const BYTES_LEFT_OFF_2_STE: u32 = 20;
    /// Byte effect of [`RIGHT_OFF`] (`video.h`, `BORDERBYTES_RIGHT`).
    pub const BYTES_RIGHT_OFF: u32 = 44;
    /// Byte effect of the [`LEFT_PLUS_2`]/[`RIGHT_MINUS_2`] nudges
    /// (`video.h`, derived from the 4-cycle = 2-byte difference between
    /// the 50Hz/60Hz thresholds).
    pub const BYTES_NUDGE: u32 = 2;
    /// Byte effect (reduction) of [`STOP_MIDDLE`] (`video.h`,
    /// `BORDERBYTES_NORMAL`(160) - `BORDERBYTES_MIDDLE`(54) = 106, or
    /// directly the "-106" documented in Hatari).
    pub const BYTES_STOP_MIDDLE: u32 = 106;
    /// Byte effect of [`RIGHT_OFF_FULL`], ON TOP OF
    /// [`BYTES_RIGHT_OFF`] (`video.h`, `BORDERBYTES_RIGHT_FULL`).
    pub const BYTES_RIGHT_OFF_FULL: u32 = 22;
}

/// Complete state of a Shifter.
#[derive(Debug, Clone)]
pub struct Shifter {
    video_base: u32,
    video_counter: u32,
    resolution: Resolution,
    /// 16 colors. Raw format depends on [`Self::ste_palette`]: ST (9 bits,
    /// 8-10=R/4-6=G/0-2=B, 3 bits each) or STE (12 bits, 8-11=R/4-7=G/0-3=B,
    /// 4 bits each, contiguous nibbles).
    palette: [u16; 16],
    /// STE extended palette (12 bits/4 per component) instead of the
    /// original ST format (9 bits/3 per component) — see
    /// [`Self::set_ste_palette`].
    ste_palette: bool,
    /// Current EFFECTIVE fine-scroll offset (0-15) — see
    /// [`Self::write_hscroll`]. An ordinary register (not a silicon
    /// characteristic like `ste_palette`), reset to zero by
    /// [`Self::reset`].
    h_scroll_count: u8,
    /// `true` if the current effective offset comes from `$FF8265` (with
    /// prefetch), `false` if from `$FF8264` (without) — see
    /// [`Self::write_hscroll`].
    h_scroll_prefetch: bool,
    /// Current EFFECTIVE line width (raw `$FF820F`) — see
    /// [`Self::write_line_width`].
    line_width: u8,
    /// Pending offset/prefetch, applied at the end-of-
    /// [`Self::render_scanline`] COMMIT (so effective starting from the
    /// next line) — see [`Self::write_hscroll`].
    pending_h_scroll: Option<(u8, bool)>,
    /// Pending line width, same mechanism as
    /// [`Self::pending_h_scroll`] — see [`Self::write_line_width`].
    pending_line_width: Option<u8>,
    /// Border mask accumulated WHILE scanning the current line ([`border`]
    /// bits) — see [`Self::write_resolution`]/
    /// [`Self::write_sync`], consumed and reset to zero (or re-armed by
    /// [`Self::pending_left_off_next_line`]) at the end of
    /// [`Self::render_scanline`].
    border_mask: u32,
    /// `true` if a [`border::RIGHT_OFF_FULL`] triggered on the current
    /// line must force [`border::LEFT_OFF_2_STE`] at the BEGINNING of the
    /// NEXT line (cross-line cascade, Hatari-style, which writes directly
    /// into `ShifterLines[HblCounterVideo+1]`) — see
    /// [`Self::write_resolution`], consumed at the end of
    /// [`Self::render_scanline`].
    pending_left_off_next_line: bool,
    /// History (cycle, raw value 0-2) of `$FF8260` writes on the current
    /// line — needed by [`Self::detect_med_res_tricks`] (Steem SSE-style,
    /// see the module doc), which measures the number of cycles ACTUALLY
    /// elapsed between successive resolution changes, unlike the other
    /// mechanisms above which react to a fixed threshold on each write.
    /// Fed by [`Self::write_resolution`], reset to zero at the end of
    /// [`Self::render_scanline`].
    resolution_write_history: Vec<(u32, u8)>,
    /// Signed byte offset of the left border's read position, computed by
    /// [`Self::detect_med_res_tricks`] — see the module doc. Distinct from
    /// [`Self::border_left_bytes`]: affects ONLY the read position
    /// (`start`, Steem's `SHIFT_SDP`-style), not the displayed width nor
    /// the video counter advance.
    med_res_byte_shift: i32,
}

impl Default for Shifter {
    fn default() -> Self {
        Self::new()
    }
}

impl Shifter {
    pub fn new() -> Self {
        Shifter {
            video_base: 0,
            video_counter: 0,
            resolution: Resolution::Low,
            palette: [0; 16],
            ste_palette: false,
            h_scroll_count: 0,
            h_scroll_prefetch: false,
            line_width: 0,
            pending_h_scroll: None,
            pending_line_width: None,
            border_mask: 0,
            pending_left_off_next_line: false,
            resolution_write_history: Vec::new(),
            med_res_byte_shift: 0,
        }
    }

    /// Enables/disables the STE extended palette format (12 bits) — to be
    /// called right after construction based on
    /// [`crate::systems::atari_st::model::MachineProfile::ste_palette`].
    pub fn set_ste_palette(&mut self, on: bool) {
        self.ste_palette = on;
    }

    /// Writes `$FF8264` (`prefetch=false`) or `$FF8265` (`prefetch=true`) —
    /// STE horizontal fine scrolling, 0-15 pixels. `apply_now` decides
    /// whether the value applies to the line CURRENTLY being scanned or
    /// is deferred to the next one (see [`Self::render_scanline`]):
    /// computed by the caller (the board, the only one that knows the
    /// cycle position within the line via
    /// `Glue::cycles_in_line`/`line_start_cycle` — reproduces Hatari's
    /// "gating" threshold, `video.c`, `Video_HorScroll_Write`).
    pub fn write_hscroll(&mut self, value: u8, prefetch: bool, apply_now: bool) {
        let value = value & 0x0F;
        if apply_now {
            self.h_scroll_count = value;
            self.h_scroll_prefetch = prefetch;
            self.pending_h_scroll = None;
        } else {
            self.pending_h_scroll = Some((value, prefetch));
        }
    }

    /// Writes `$FF820F` (STE line width) — same immediate/deferred
    /// mechanism as [`Self::write_hscroll`], but gated by the caller on
    /// `Glue::line_end_cycle` (end of active display), not
    /// `line_start_cycle` (see `video.c`, `Video_LineWidth_WriteByte`).
    pub fn write_line_width(&mut self, value: u8, apply_now: bool) {
        if apply_now {
            self.line_width = value;
            self.pending_line_width = None;
        } else {
            self.pending_line_width = Some(value);
        }
    }

    /// Writes `$FF8260` (resolution) with knowledge of the cycle position
    /// within the line — to be called by the board instead of a direct
    /// [`Self::write`], to detect the horizontal border tricks triggered
    /// by a switch to high resolution, Hatari `Video_Update_Glue_State`-
    /// style (see the module doc):
    /// - `cycles_in_line <= 4`: arms [`border::LEFT_OFF_PENDING`]; a
    ///   return to low/medium resolution EXACTLY at cycle 4 converts it
    ///   into [`border::LEFT_OFF_2_STE`] (+20 bytes of left border
    ///   revealed). Any other return to low/medium resolution cancels the
    ///   attempt.
    /// - `4 < cycles_in_line <= 164`: arms [`border::STOP_MIDDLE`] (line
    ///   shortened by 106 bytes) directly, no confirmation needed.
    ///   Cancellable by a return to low/medium resolution as long as
    ///   `cycles_in_line <= 164` (before the "point of no return" — past
    ///   this cycle, the line has already been cut, a resolution change
    ///   no longer has any effect).
    /// - `164 < cycles_in_line <= 376`: arms [`border::RIGHT_OFF`] +
    ///   [`border::RIGHT_OFF_FULL`] (right border TOTALLY removed,
    ///   +44+22 bytes) AND forces [`border::LEFT_OFF_2_STE`] at the
    ///   BEGINNING of the NEXT line (cascade, see
    ///   [`Self::pending_left_off_next_line`]) — once triggered, this
    ///   mechanism is NOT cancellable by a return to low/medium
    ///   resolution later in the same line (documented simplification:
    ///   Hatari has a cancellation window via `$FF820A`, not modeled
    ///   here, see the module doc).
    pub fn write_resolution(&mut self, value: u8, cycles_in_line: u32) {
        let new_res = Resolution::from_bits(value);
        // History for `detect_med_res_tricks` (Steem SSE-style, see the
        // module doc) — independent of the `border_mask` logic below,
        // which remains faithful to Hatari.
        self.resolution_write_history.push((cycles_in_line, value & 0b11));
        if new_res == Resolution::High {
            if cycles_in_line <= border::HDE_ON_HI {
                self.border_mask |= border::LEFT_OFF_PENDING;
            } else if cycles_in_line <= border::HDE_OFF_HI {
                self.border_mask |= border::STOP_MIDDLE;
                self.border_mask &= !border::RIGHT_MINUS_2;
            } else if cycles_in_line <= border::HDE_OFF_LOW_50 {
                self.border_mask |= border::RIGHT_OFF | border::RIGHT_OFF_FULL;
                self.pending_left_off_next_line = true;
            }
        } else if cycles_in_line == border::HDE_ON_HI && self.border_mask & border::LEFT_OFF_PENDING != 0 {
            self.border_mask = (self.border_mask & !border::LEFT_OFF_PENDING) | border::LEFT_OFF_2_STE;
        } else {
            self.border_mask &= !border::LEFT_OFF_PENDING;
            if cycles_in_line <= border::HDE_OFF_HI {
                self.border_mask &= !border::STOP_MIDDLE;
            }
        }
        self.resolution = new_res;
    }

    /// Writes `$FF820A` (GLUE sync register) on the Shifter side —
    /// distinct from [`crate::peripherals::atari_st::glue::Glue::write_sync`]
    /// (VERTICAL overscan): here, the HORIZONTAL effects
    /// ([`border::RIGHT_OFF`], [`border::LEFT_PLUS_2`]/
    /// [`border::RIGHT_MINUS_2`] nudges), Hatari `Video_Update_Glue_State`-
    /// style (see the module doc). The register is physically UNIQUE: the
    /// board must call BOTH methods (`Glue::write_sync` and this one) on
    /// every `$FF820A` write.
    ///
    /// A return to 50Hz does NOT cancel everything at once: each
    /// mechanism has its OWN cancellation window, taken from Hatari
    /// (`Video_Update_Glue_State`): [`border::LEFT_PLUS_2`] only if
    /// `cycles_in_line <= HDE_On_Low_60`(52); [`border::RIGHT_MINUS_2`] and
    /// [`border::RIGHT_OFF`] only if `cycles_in_line <=
    /// HDE_Off_Low_50`(376) — for `RIGHT_OFF`, this window is in
    /// practice very narrow: the bit is armed ONLY within
    /// `]HDE_Off_Low_60(372), HDE_Off_Low_50(376)]`, so only a second
    /// `$FF820A` write occurring a few cycles after the trigger, within
    /// the SAME window, can still cancel it — past cycle 376, the effect
    /// is locked in for the rest of the line (behavior confirmed against
    /// `video.c`, not an approximation).
    pub fn write_sync(&mut self, value: u8, cycles_in_line: u32) {
        let selecting_60hz = value & 0x02 == 0;
        if selecting_60hz {
            if cycles_in_line > border::HDE_OFF_LOW_60 && cycles_in_line <= border::HDE_OFF_LOW_50 {
                self.border_mask |= border::RIGHT_OFF;
            }
            if cycles_in_line <= border::PRELOAD_START_LOW_60 {
                self.border_mask |= border::LEFT_PLUS_2 | border::RIGHT_MINUS_2;
            }
        } else {
            if cycles_in_line <= border::HDE_ON_LOW_60 {
                self.border_mask &= !border::LEFT_PLUS_2;
            }
            if cycles_in_line <= border::HDE_OFF_LOW_50 {
                self.border_mask &= !(border::RIGHT_MINUS_2 | border::RIGHT_OFF);
            }
        }
    }

    /// Border mask accumulated for the line CURRENTLY being scanned
    /// ([`border`] bits) — external diagnostics/tests.
    pub fn border_mask(&self) -> u32 {
        self.border_mask
    }

    /// Analyzes [`Self::resolution_write_history`] to detect
    /// [`border::OVERSCAN_MED_RES`]/[`border::FOUR_BIT_SCROLL`] — Steem
    /// SSE-style (`TGlue::CheckSideOverscan`, `glue.cpp`), NOT Hatari, see
    /// the module doc. Called once per line, at the start of
    /// [`Self::render_scanline`] (Steem analyzes the line's complete
    /// history after the fact, not write-by-write like the other
    /// mechanisms in this module).
    ///
    /// Precondition (confirmed in the Steem code: `!left_border`): these
    /// two tricks refine a left border already revealed by
    /// [`border::LEFT_OFF_2_STE`], they do not trigger it themselves —
    /// does nothing if it is not already active.
    ///
    /// `OVERSCAN_MED_RES`: the last switch to medium resolution (value
    /// `0b01`) within the window `]24, 48]`, preceded by ANOTHER
    /// resolution change, shifts the read position by
    /// `-(((cycles_in_low_res / 2) % 8) / 2)` bytes, `cycles_in_low_res`
    /// being the number of cycles between that preceding change and the
    /// switch to medium resolution.
    ///
    /// `FOUR_BIT_SCROLL`: same trigger (last switch to medium
    /// resolution), window `[16, 48]`, but ALSO looks at the NEXT change
    /// (return to low resolution) to measure the time spent in medium
    /// resolution (`cycles_in_med_res`); shifts the read position by
    /// `8 - cycles_in_med_res/2 + cycles_in_low_res/4` bytes. The two
    /// effects stack if both tricks trigger on the same line (as in
    /// Steem, where both call `SHIFT_SDP` without excluding each other).
    fn detect_med_res_tricks(&mut self) {
        if self.border_mask & border::LEFT_OFF_2_STE == 0 {
            return;
        }
        let history = &self.resolution_write_history;

        if let Some(r1) = Self::cycle_of_last_change_to(history, 0b01) {
            if r1 > border::MEDRES_OA && r1 <= border::MEDRES_OB {
                if let Some(r0) = Self::previous_change(history, r1) {
                    let cycles_in_low_res = (r1 - r0) as i32;
                    self.med_res_byte_shift -= ((cycles_in_low_res / 2) % 8) / 2;
                    self.border_mask |= border::OVERSCAN_MED_RES;
                }
            }
        }

        if let Some(r1) = Self::cycle_of_last_change_to(history, 0b01) {
            if r1 >= border::MEDRES_OC && r1 <= border::MEDRES_OB {
                if let Some(r0_next) = Self::next_change(history, r1) {
                    if r0_next <= border::MEDRES_OB {
                        let cycles_in_med_res = (r0_next - r1) as i32;
                        let cycles_in_low_res = Self::previous_change(history, r1)
                            .map(|r0_prev| (r1 - r0_prev) as i32)
                            .unwrap_or(0);
                        self.med_res_byte_shift += 8 - cycles_in_med_res / 2 + cycles_in_low_res / 4;
                        self.border_mask |= border::FOUR_BIT_SCROLL;
                    }
                }
            }
        }
    }

    /// Cycle of the LAST resolution change to `mode` (`0b00`-`0b10`) in
    /// the history — Steem-style, `CycleOfLastChangeToShiftMode`.
    /// `history` must be sorted by increasing cycle (guaranteed by
    /// [`Self::write_resolution`], which only ever appends).
    fn cycle_of_last_change_to(history: &[(u32, u8)], mode: u8) -> Option<u32> {
        history.iter().rev().find(|&&(_, m)| m == mode).map(|&(c, _)| c)
    }

    /// Cycle of the change STRICTLY BEFORE `cycle`, any mode — Steem-style,
    /// `PreviousShiftModeChange`.
    fn previous_change(history: &[(u32, u8)], cycle: u32) -> Option<u32> {
        history.iter().rev().map(|&(c, _)| c).find(|&c| c < cycle)
    }

    /// Cycle of the change STRICTLY AFTER `cycle`, any mode — Steem-style,
    /// `NextShiftModeChange`.
    fn next_change(history: &[(u32, u8)], cycle: u32) -> Option<u32> {
        history.iter().map(|&(c, _)| c).find(|&c| c > cycle)
    }

    /// Left border bytes to reveal for the current line, based on
    /// [`Self::border_mask`] — see [`Self::render_scanline`].
    fn border_left_bytes(&self) -> u32 {
        let mut bytes = 0;
        if self.border_mask & border::LEFT_OFF_2_STE != 0 {
            bytes += border::BYTES_LEFT_OFF_2_STE;
        }
        if self.border_mask & border::LEFT_PLUS_2 != 0 {
            bytes += border::BYTES_NUDGE;
        }
        bytes
    }

    /// Right border bytes to reveal for the current line, based on
    /// [`Self::border_mask`] — see [`Self::render_scanline`].
    fn border_right_bytes(&self) -> u32 {
        let mut bytes = 0;
        if self.border_mask & border::RIGHT_OFF != 0 {
            bytes += border::BYTES_RIGHT_OFF;
        }
        if self.border_mask & border::RIGHT_OFF_FULL != 0 {
            bytes += border::BYTES_RIGHT_OFF_FULL;
        }
        let minus_2 = if self.border_mask & border::RIGHT_MINUS_2 != 0 { border::BYTES_NUDGE } else { 0 };
        bytes.saturating_sub(minus_2)
    }

    /// Bytes to SUBTRACT from the central segment for the current line,
    /// based on [`Self::border_mask`] — see [`Self::render_scanline`].
    fn border_center_reduction_bytes(&self) -> u32 {
        if self.border_mask & border::STOP_MIDDLE != 0 { border::BYTES_STOP_MIDDLE } else { 0 }
    }

    /// Current effective fine-scroll offset (0-15) — external
    /// diagnostics/tests.
    pub fn h_scroll_count(&self) -> u8 {
        self.h_scroll_count
    }

    /// `true` if the current effective offset comes from `$FF8265` (with
    /// prefetch) — external diagnostics/tests.
    pub fn h_scroll_prefetch(&self) -> bool {
        self.h_scroll_prefetch
    }

    /// Current effective line width (raw `$FF820F`) — external
    /// diagnostics/tests.
    pub fn line_width(&self) -> u8 {
        self.line_width
    }

    /// Resets the internal state (registers/counter/palette) following a
    /// hardware `/RESET`, preserving [`Self::ste_palette`]: unlike the
    /// registers, the presence of the STE extended palette is a silicon
    /// characteristic (which Shifter is physically present in the
    /// machine), not state cleared by a RESET pulse — replacing the whole
    /// instance with `Shifter::new()` (as a previous version of
    /// `AtariSt::reset_bus` did) lost this setting on every execution of
    /// the RESET instruction (the TOS executes one at startup), which
    /// silently switched the whole session back to the ST palette format
    /// (9 bits) on an STE machine.
    pub fn reset(&mut self) {
        let ste_palette = self.ste_palette;
        *self = Self::new();
        self.ste_palette = ste_palette;
    }

    fn palette_mask(&self) -> u16 {
        if self.ste_palette { 0x0FFF } else { 0x0777 }
    }

    pub fn resolution(&self) -> Resolution {
        self.resolution
    }

    /// The 16 raw palette words (see [`Self::color_to_rgb`] for their
    /// decoding) — useful for external diagnostics (see `RUST68_DEBUG`
    /// in `atari_st_sdl2`).
    pub fn palette_raw(&self) -> &[u16; 16] {
        &self.palette
    }

    /// Current 24-bit RGB border color — on a real ST/STE, the border
    /// (the area outside the active window, always visible on a real
    /// monitor) has no dedicated register: it simply displays palette
    /// color 0, like any pixel programmed to index 0. Used by the SDL2
    /// frontend to paint the border margin around the active image.
    pub fn border_color(&self) -> (u8, u8, u8) {
        self.color_to_rgb(self.palette[0])
    }

    /// Current video base address (register, see [`addr::VIDEO_BASE_HIGH`]/
    /// [`addr::VIDEO_BASE_MID`]) — external diagnostics.
    pub fn video_base(&self) -> u32 {
        self.video_base
    }

    /// Current video counter — external diagnostics.
    pub fn video_counter(&self) -> u32 {
        self.video_counter
    }

    /// Reads the register at bus address `addr` (see [`addr`]).
    pub fn read(&self, bus_addr: u32) -> u8 {
        match bus_addr {
            addr::VIDEO_BASE_HIGH => (self.video_base >> 16) as u8,
            addr::VIDEO_BASE_MID => (self.video_base >> 8) as u8,
            addr::VIDEO_BASE_LOW => self.video_base as u8,
            addr::VIDEO_COUNTER_HIGH => (self.video_counter >> 16) as u8,
            addr::VIDEO_COUNTER_MID => (self.video_counter >> 8) as u8,
            addr::VIDEO_COUNTER_LOW => self.video_counter as u8,
            addr::RESOLUTION => self.resolution.to_bits(),
            _ if (addr::PALETTE_BASE..addr::PALETTE_BASE + 32).contains(&bus_addr) => {
                let color = ((bus_addr - addr::PALETTE_BASE) / 2) as usize;
                let word = self.palette[color];
                if (bus_addr - addr::PALETTE_BASE) % 2 == 0 {
                    (word >> 8) as u8
                } else {
                    word as u8
                }
            }
            _ => 0xFF,
        }
    }

    /// Writes the register at bus address `addr` (see [`addr`]).
    pub fn write(&mut self, bus_addr: u32, value: u8) {
        match bus_addr {
            addr::VIDEO_BASE_HIGH => {
                self.video_base = (self.video_base & 0x00FFFF) | ((value as u32) << 16)
            }
            addr::VIDEO_BASE_MID => {
                self.video_base = (self.video_base & 0xFF00FF) | ((value as u32) << 8)
            }
            addr::VIDEO_BASE_LOW => self.video_base = (self.video_base & 0xFFFF00) | value as u32,
            addr::VIDEO_COUNTER_HIGH => {
                self.video_counter = (self.video_counter & 0x00FFFF) | ((value as u32) << 16)
            }
            addr::VIDEO_COUNTER_MID => {
                self.video_counter = (self.video_counter & 0xFF00FF) | ((value as u32) << 8)
            }
            addr::VIDEO_COUNTER_LOW => {
                self.video_counter = (self.video_counter & 0xFFFF00) | value as u32
            }
            addr::RESOLUTION => self.resolution = Resolution::from_bits(value),
            // Writing a SINGLE byte to a palette register: on real
            // silicon (confirmed by Hatari, `Video_ColorReg_WriteWord`,
            // comment giving `move.b #7,$ff8240 -> color 0 = $707`), the
            // written byte is duplicated into BOTH halves of the word
            // BEFORE masking — the other half is NOT preserved. A
            // previous version only touched the half actually written,
            // preserving the other: correct for a .W/.L write (see
            // [`Self::write_palette_word`], used by the board for that
            // case), but wrong for an isolated .B instruction, which
            // then overwrites the untouched half with an unrelated value
            // (e.g. red bits corrupted by a leftover from another
            // color) — consistent with a cursor/text that occasionally
            // turns red/yellow instead of staying black.
            _ if (addr::PALETTE_BASE..addr::PALETTE_BASE + 32).contains(&bus_addr) => {
                let color = ((bus_addr - addr::PALETTE_BASE) / 2) as usize;
                let duplicated = ((value as u16) << 8) | value as u16;
                self.palette[color] = duplicated & self.palette_mask();
                if std::env::var("RUST68_TRACE_PALETTE").is_ok() {
                    eprintln!(
                        "[palette] .B addr={bus_addr:#08x} color={color} value={value:#04x} -> {:#06x}",
                        self.palette[color]
                    );
                }
            }
            _ => {}
        }
    }

    /// Writes a full word (16 bits) to a palette register — path
    /// used by the board for `.W`/`.L` CPU accesses (unlike
    /// [`Self::write`], which only ever sees one byte at a time and thus
    /// always assumes an isolated `.B` access; see the byte duplication
    /// documented there). `bus_addr` must be the even address of the
    /// register.
    pub fn write_palette_word(&mut self, bus_addr: u32, value: u16) {
        let color = ((bus_addr - addr::PALETTE_BASE) / 2) as usize;
        self.palette[color] = value & self.palette_mask();
        if std::env::var("RUST68_TRACE_PALETTE").is_ok() {
            eprintln!(
                "[palette] .W addr={bus_addr:#08x} color={color} value={value:#06x} -> {:#06x}",
                self.palette[color]
            );
        }
    }

    /// Reloads the video counter from the base address — to be called by
    /// the board on every VBL.
    pub fn start_frame(&mut self) {
        self.video_counter = self.video_base;
    }

    /// Reads the next video RAM line from the current counter, converts
    /// it into 24-bit RGB pixels according to the programmed resolution,
    /// and advances the counter by the number of bytes consumed. To be
    /// called by the board on every HBL.
    ///
    /// `ram` must cover at least `video_counter` + the number of bytes
    /// actually consumed by this line (`resolution.bytes_per_line()`,
    /// plus one group of 16 pixels if STE prefetch is active, see
    /// [`Self::write_hscroll`]) — returns a line of zeros (black) if that
    /// is not the case, rather than panicking (end of installed RAM, or
    /// video base pointed beyond it by test software). The counter
    /// itself ALWAYS advances (even before knowing whether the read will
    /// succeed): on real silicon, the Shifter's address counter is a
    /// simple address generator, independent of the physical presence of
    /// RAM at that exact address — only the content read depends on it,
    /// not the counter's advance. NOT advancing it here stalled the
    /// counter indefinitely (and hence every software read of
    /// `VIDEO_COUNTER_*`) as soon as the video base exceeded the
    /// installed RAM — confirmed necessary by the STE factory diagnostic
    /// cartridge (test "T4 Video Counter in Memory Controller", which
    /// deliberately moves the video base to the very end of installed
    /// RAM to verify that the counter keeps advancing correctly).
    pub fn render_scanline(&mut self, ram: &[u8]) -> Vec<(u8, u8, u8)> {
        // Must run BEFORE the `left_bytes`/`start` computation below:
        // Steem-style, the line's complete history is analyzed once, not
        // write-by-write (see the doc of `detect_med_res_tricks`).
        self.detect_med_res_tricks();
        let planes = self.resolution.planes();
        let bytes_per_group = planes * 2;
        // STE prefetch active ($FF8265, nonzero offset): one EXTRA group
        // of 16 pixels is actually read (and consumed on the address
        // counter) per line to fill the right edge — see the doc of
        // [`Self::write_hscroll`] and [`Self::scroll_src_bit`].
        let extra_group = self.h_scroll_count > 0 && self.h_scroll_prefetch;
        // `STOP_MIDDLE` (see [`border`]) shortens the central segment
        // (line interrupted by a high-resolution switch partway through)
        // — subtracted BEFORE adding the prefetch, as Hatari does
        // (`BORDERBYTES_NORMAL - BORDERBYTES_STOP_MIDDLE`).
        let center_bytes = (self.resolution.bytes_per_line())
            .saturating_sub(self.border_center_reduction_bytes() as usize)
            + if extra_group { bytes_per_group } else { 0 };
        // Left/right border ($FF8260/$FF820A, see [`border`] and the
        // module doc): extra bytes revealed on either side of the
        // central segment, in addition to the fine scrolling above.
        let left_bytes = self.border_left_bytes() as usize;
        let right_bytes = self.border_right_bytes() as usize;
        let bytes_this_line = left_bytes + center_bytes + right_bytes;
        // The left border is read BEFORE the nominal counter position
        // (the bytes it reveals "precede" the usual display start); the
        // counter itself advances as if only the RIGHT extension had
        // occurred — simplified model, not verified against the exact
        // detail of Hatari's `pVideoRaster`/`nVideoCounter` divergence
        // (see the documented limitations at the top of the module).
        // `med_res_byte_shift` (Steem-style, `SHIFT_SDP`) FURTHER refines
        // this read position without changing the displayed width or the
        // counter advance — see `detect_med_res_tricks`.
        let start = (self.video_counter as i64 - left_bytes as i64 + self.med_res_byte_shift as i64).max(0) as usize;
        // `LineWidth` ($FF820F): extra bytes added to the address advance
        // at the END of the line (virtual screen wider than the display),
        // on top of the bytes actually displayed/prefetched above — see
        // Hatari, `video.c`, `pVideoRaster += LineWidth*2`.
        self.video_counter += (center_bytes + right_bytes + self.line_width as usize * 2) as u32;
        // Width (in pixels) of the CENTRAL segment to produce: normally
        // `resolution.width()`, reduced by `STOP_MIDDLE` — independent of
        // fine-scroll prefetch (which adds bytes READ, not displayed, see
        // the doc of [`Self::render_planar`]).
        let center_width = self.resolution.bytes_per_line().saturating_sub(self.border_center_reduction_bytes() as usize)
            * 8
            / planes.max(1);

        let pixels = match ram.get(start..start + bytes_this_line) {
            Some(line) => {
                let (left, rest) = line.split_at(left_bytes);
                let (center, right) = rest.split_at(center_bytes);
                match self.resolution {
                    Resolution::High => self.render_mono_full(left, center, right, center_width),
                    _ => self.render_planar_full(left, center, right, planes, center_width),
                }
            }
            None => {
                let width = center_width + (left_bytes + right_bytes) * 8 / planes.max(1);
                vec![(0, 0, 0); width]
            }
        };

        // Commit the pending scroll/width values (writes that occurred
        // too late in THIS line to apply to it, see the board-side
        // cycle-exact "gating"): effective starting from the NEXT line —
        // reproduces Hatari's `New*` mechanism.
        if let Some((count, prefetch)) = self.pending_h_scroll.take() {
            self.h_scroll_count = count;
            self.h_scroll_prefetch = prefetch;
        }
        if let Some(width) = self.pending_line_width.take() {
            self.line_width = width;
        }
        // The border mask only covers the line it just helped render —
        // reset to zero (or re-armed with `LEFT_OFF_2_STE` if
        // `RIGHT_OFF_FULL` just forced the cascade onto THIS next line,
        // see `write_resolution`), then re-accumulated by the next
        // line's writes.
        self.border_mask = if self.pending_left_off_next_line { border::LEFT_OFF_2_STE } else { 0 };
        self.pending_left_off_next_line = false;
        self.resolution_write_history.clear();
        self.med_res_byte_shift = 0;

        pixels
    }

    /// Source bit position in `line` for output pixel `x`, accounting
    /// for the current effective STE fine scrolling — see the doc of
    /// [`Self::write_hscroll`]. `None` if this pixel must output color
    /// index 0 without a read (left edge blanked in no-prefetch mode,
    /// the hardware shift register not having had time to load yet —
    /// `$FF8264`, see Hatari `video.c`, comment on `HWScrollPrefetch=0`).
    fn scroll_src_bit(&self, x: usize) -> Option<usize> {
        let scroll = self.h_scroll_count as usize;
        if scroll == 0 {
            return Some(x); // passthrough: unchanged historical behavior
        }
        if self.h_scroll_prefetch {
            Some(x + scroll) // buffer extended by one group, see render_scanline
        } else if x < 16 {
            None // shift register not loaded yet: black
        } else {
            Some((x - 16) + scroll) // normal buffer, no extra bytes
        }
    }

    /// Color index (0-15) at source bit `src_bit` of `line`, standard
    /// word-interleaved planar decoding — factored out for reuse by both
    /// [`Self::render_planar`] (central segment, with fine scrolling via
    /// [`Self::scroll_src_bit`]) and [`Self::render_planar_full`] (left/
    /// right border segments, direct addressing without scrolling).
    fn planar_color_index(line: &[u8], planes: usize, src_bit: usize) -> u8 {
        let group = src_bit / 16;
        let bit_in_group = 15 - (src_bit % 16);
        let mut color_index = 0u8;
        for plane in 0..planes {
            let byte_offset = group * planes * 2 + plane * 2;
            if let (Some(&hi), Some(&lo)) = (line.get(byte_offset), line.get(byte_offset + 1)) {
                let word = u16::from_be_bytes([hi, lo]);
                color_index |= (((word >> bit_in_group) & 1) as u8) << plane;
            }
        }
        color_index
    }

    /// RGB pixel at source bit `src_bit` of `line` in high-resolution
    /// monochrome mode — factored out the same way as
    /// [`Self::planar_color_index`], see [`Self::render_mono`]/
    /// [`Self::render_mono_full`].
    fn mono_pixel(line: &[u8], src_bit: usize) -> (u8, u8, u8) {
        let group = src_bit / 16;
        let bit_in_group = 15 - (src_bit % 16);
        let byte_offset = group * 2;
        let set = match (line.get(byte_offset), line.get(byte_offset + 1)) {
            (Some(&hi), Some(&lo)) => (u16::from_be_bytes([hi, lo]) >> bit_in_group) & 1 != 0,
            _ => false,
        };
        // Convention: bit set to 1 = black, 0 = white (see limitations).
        if set { (0, 0, 0) } else { (255, 255, 255) }
    }

    /// `width`: number of pixels to produce for this segment — NORMALLY
    /// [`Resolution::width`], but reduced by [`Self::render_scanline`]
    /// when [`border::STOP_MIDDLE`] shortens the line (fine scrolling
    /// does NOT change `width`, only the source addressing via
    /// [`Self::scroll_src_bit`] — see the doc of [`Self::render_scanline`]).
    fn render_planar(&self, line: &[u8], width: usize) -> Vec<(u8, u8, u8)> {
        let planes = self.resolution.planes();
        let mut pixels = Vec::with_capacity(width);
        for x in 0..width {
            let Some(src_bit) = self.scroll_src_bit(x) else {
                pixels.push(self.color_to_rgb(self.palette[0]));
                continue;
            };
            let color_index = Self::planar_color_index(line, planes, src_bit);
            pixels.push(self.color_to_rgb(self.palette[color_index as usize]));
        }
        pixels
    }

    /// See the doc of [`Self::render_planar`] for `width`.
    fn render_mono(&self, line: &[u8], width: usize) -> Vec<(u8, u8, u8)> {
        let mut pixels = Vec::with_capacity(width);
        for x in 0..width {
            let Some(src_bit) = self.scroll_src_bit(x) else {
                pixels.push((255, 255, 255)); // mono "edge black" = bit 0 = white, see the convention below
                continue;
            };
            pixels.push(Self::mono_pixel(line, src_bit));
        }
        pixels
    }

    /// Renders a complete planar line, including left/right border (see
    /// [`border`] and the module doc): the border segments are decoded
    /// directly (sequential addressing, no fine scrolling), the central
    /// segment via [`Self::render_planar`] (fine scrolling applicable).
    /// `left`/`center`/`right` are disjoint sub-slices of the RAM line
    /// read by [`Self::render_scanline`], `center_width` is the number of
    /// pixels to produce for the central segment (see the doc of
    /// [`Self::render_planar`]).
    fn render_planar_full(
        &self,
        left: &[u8],
        center: &[u8],
        right: &[u8],
        planes: usize,
        center_width: usize,
    ) -> Vec<(u8, u8, u8)> {
        let mut pixels = Vec::with_capacity((left.len() + right.len()) * 8 / planes.max(1) + center_width);
        pixels.extend(self.render_planar_border_segment(left, planes));
        pixels.extend(self.render_planar(center, center_width));
        pixels.extend(self.render_planar_border_segment(right, planes));
        pixels
    }

    /// Decodes a border segment (left or right): direct sequential
    /// addressing, no fine scrolling (see the limitation documented in
    /// the module doc).
    fn render_planar_border_segment(&self, segment: &[u8], planes: usize) -> Vec<(u8, u8, u8)> {
        (0..segment.len() * 8 / planes.max(1))
            .map(|x| {
                let color_index = Self::planar_color_index(segment, planes, x);
                self.color_to_rgb(self.palette[color_index as usize])
            })
            .collect()
    }

    /// Equivalent of [`Self::render_planar_full`] for monochrome high
    /// resolution.
    fn render_mono_full(&self, left: &[u8], center: &[u8], right: &[u8], center_width: usize) -> Vec<(u8, u8, u8)> {
        let mut pixels = Vec::with_capacity(left.len() * 8 + right.len() * 8 + center_width);
        for x in 0..left.len() * 8 {
            pixels.push(Self::mono_pixel(left, x));
        }
        pixels.extend(self.render_mono(center, center_width));
        for x in 0..right.len() * 8 {
            pixels.push(Self::mono_pixel(right, x));
        }
        pixels
    }

    /// Converts a raw palette word into 24-bit RGB, by bit replication
    /// (0..2^n-1 -> 0..255 exactly, not just an approximate scaling) — 3
    /// bits/component on ST (`$RGB` over 9 bits), 4 bits/component on STE
    /// (`$RGB` over 12 bits, contiguous nibbles but NOT in the naive
    /// order, see [`ste_nibble_to_intensity`] — real bug found and fixed
    /// here, see its doc).
    fn color_to_rgb(&self, word: u16) -> (u8, u8, u8) {
        if self.ste_palette {
            let r4 = ((word >> 8) & 0x0F) as u8;
            let g4 = ((word >> 4) & 0x0F) as u8;
            let b4 = (word & 0x0F) as u8;
            (expand4(ste_nibble_to_intensity(r4)), expand4(ste_nibble_to_intensity(g4)), expand4(ste_nibble_to_intensity(b4)))
        } else {
            let r3 = ((word >> 8) & 0x07) as u8;
            let g3 = ((word >> 4) & 0x07) as u8;
            let b3 = (word & 0x07) as u8;
            (expand3(r3), expand3(g3), expand3(b3))
        }
    }
}

/// Replicates a 3-bit value (0-7) into 8 bits (0-255): `v<<5 | v<<2 | v>>1`
/// gives exactly 0 and 255 at the extremes and a regular progression
/// in between, rather than a mere approximate multiplication.
fn expand3(v: u8) -> u8 {
    (v << 5) | (v << 2) | (v >> 1)
}

/// Replicates a 4-bit value (0-15) into 8 bits (0-255): `v<<4 | v` gives
/// exactly 0 and 255 at the extremes and a regular progression.
fn expand4(v: u8) -> u8 {
    (v << 4) | v
}

/// Reorders a raw STE palette nibble (bits 3-0 of a color register) into
/// the actual 4-bit intensity it represents — **real bug fixed here**:
/// bit 3 of the nibble is NOT the high-order bit of a normal 4-bit value,
/// it is a fine-precision bit ADDED AT THE BOTTOM by the STE hardware, to
/// stay compatible with the original ST's 3-bit format (bits 2-0, which
/// occupy the SAME bus positions as on ST). The actual intensity is thus
/// `(bits2-0 << 1) | bit3`, not the nibble read as-is. Confirmed against
/// Hatari (`conv_st.c`, `ConvST_SetupRGBTable`:
/// `rr = ((r & 0x7) << 1) | ((r & 0x8) >> 3)`).
///
/// Before this fix, a nibble `0b0111` (the "ST-style" maximum, what an
/// STE game would naturally write wanting a component at full 3-bit
/// intensity) was read as the 4-bit value `7` and produced an RGB of
/// ~47% (119/255) instead of ~93% (238/255, one notch below the true
/// maximum 15/15) — a systematic and severe darkening of any STE palette
/// built this way, consistent with game colors reported as "very dark".
fn ste_nibble_to_intensity(nibble: u8) -> u8 {
    let low3 = nibble & 0x07;
    let fine_bit = (nibble >> 3) & 0x01;
    (low3 << 1) | fine_bit
}
